# Generated by Django 4.0.2 on 2025-03-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_row_seat_and_movie_session',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='seet',
            new_name='seat',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_ticket_row_seat_and_movie_session'),
        ),
    ]
