# Generated by Django 4.0.2 on 2025-03-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_ticket_unique_ticket_row_seat_and_movie_session_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='db_order_created_331c34_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='db_order_created_f91610_idx'),
        ),
    ]
